### ISSUE TITLE
[FATAL]:22:3: The element type "link" must be terminated by the matching end-tag "</link>"

### ISSUE THREAD

**Issue by ElissandroMendes** [olap4j/olap4j#47]
Hi all,

Have you already seen this problem?

```
 java.lang.RuntimeException: [FATAL]:22:3: The element type "link" must be terminated by the matching end-tag "</link>".
    at org.olap4j.driver.xmla.XmlaOlap4jUtil.checkForParseError(XmlaOlap4jUtil.java:135)
    at org.olap4j.driver.xmla.XmlaOlap4jUtil.parse(XmlaOlap4jUtil.java:84)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.executeMetadataRequest(XmlaOlap4jConnection.java:884)
    at org.olap4j.driver.xmla.XmlaOlap4jDatabaseMetaData.getMetadata(XmlaOlap4jDatabaseMetaData.java:137)
    at org.olap4j.driver.xmla.XmlaOlap4jDatabaseMetaData.getMetadata(XmlaOlap4jDatabaseMetaData.java:67)
    at org.olap4j.driver.xmla.XmlaOlap4jDatabaseMetaData.getDatabaseProperties(XmlaOlap4jDatabaseMetaData.java:1044)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.makeConnectionPropertyList(XmlaOlap4jConnection.java:324)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.generateRequest(XmlaOlap4jConnection.java:1037)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.populateList(XmlaOlap4jConnection.java:849)
    at org.olap4j.driver.xmla.DeferredNamedListImpl.populateList(DeferredNamedListImpl.java:136)
    at org.olap4j.driver.xmla.DeferredNamedListImpl.getList(DeferredNamedListImpl.java:90)
    at org.olap4j.driver.xmla.DeferredNamedListImpl.size(DeferredNamedListImpl.java:116)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.getOlapDatabase(XmlaOlap4jConnection.java:451)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.getOlapCatalog(XmlaOlap4jConnection.java:501)
    at org.olap4j.driver.xmla.XmlaOlap4jConnection.getCatalog(XmlaOlap4jConnection.java:496)
    at org.olap4j.driver.xmla.XmlaOlap4jStatement.executeOlapQuery(XmlaOlap4jStatement.java:291)
    at MondrianTeste.main(MondrianTeste.java:18)
Caused by: org.xml.sax.SAXParseException; lineNumber: 22; columnNumber: 3; The element type "link" must be terminated by the matching end-tag "</link>".
    at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    at org.olap4j.driver.xmla.XmlaOlap4jUtil.parse(XmlaOlap4jUtil.java:81)

```

My code:

```
public class MondrianTeste {

    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        Class.forName("org.olap4j.driver.xmla.XmlaOlap4jDriver");

        Connection connection = DriverManager.getConnection("jdbc:xmla:Server=http://127.0.0.1:8080/pentaho/xmla");
        OlapConnection olapConnection = connection.unwrap(OlapConnection.class);
        OlapStatement statement = olapConnection.createStatement();

        CellSet cellSet = statement.executeOlapQuery("SELECT {([Customers].[All Customers])} ON COLUMNS FROM [SteelWheelsSales]");
        for (Position row : cellSet.getAxes().get(1)) {
            for (Position column : cellSet.getAxes().get(0)) {
                for (Member member : row.getMembers()) {
                    System.out.println(member.getUniqueName());
                }
                for (Member member : column.getMembers()) {
                    System.out.println(member.getUniqueName());
                }
                final Cell cell = cellSet.getCell(column, row);
                System.out.println(cell.getFormattedValue());
                System.out.println();
            }
        }
    }

}
```

**Comment by julianhyde** [comment]
It seems that the olap4j client is sending a DISCOVER_PROPERTIES metadata request and the response is invalid XML. Can you log the requests & responses and find out what that invalid XML is?
