### ISSUE TITLE
Running select in Sybase/SAP Hana fails due to incorrect Dialect

### ISSUE THREAD

**Issue by pgschr** [olap4j/olap4j#59]
This works (note that code is in Scala):     

```
      val connectionString = "jdbc:mondrian:Jdbc=jdbc:sap://10.194.19.20:39013?" + 
          "user=uuuuu&password=pppp;" + 
          "Catalog=lib/Schema.xml;JdbcDrivers=com.sap.db.jdbc.Driver"
      val connection = DriverManager.getConnection(connectionString)
      val olapConnection = connection.unwrap(classOf[OlapConnection])
		
      val parserFactory = olapConnection.getParserFactory
      val parser = parserFactory.createMdxParser(olapConnection)
      val query = parser.parseSelect(
            "select from [DDABalances] WHERE [Bank].[1]")
       val statement = olapConnection.createStatement
```
        
 However when I try to run this statement, I get an exception, because `"BANKS"."sk"` is incorrect as it shouldn't have quotes:       
```      
     val cellSet = statement.executeOlapQuery(query)
```

The exception: 

> 
> Caused by: mondrian.olap.MondrianException: Mondrian Error:Internal error: while counting members of level '[Bank].[Bank SK]; sql=[select count(*) as "c0" from (select distinct "BANKS"."sk" as "c0" from "BANKS" as "BANKS") as "init"]
>         at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:987)
>         at mondrian.olap.Util.newInternal(Util.java:2410)
>         at mondrian.olap.Util.newError(Util.java:2426)
>         at mondrian.rolap.SqlStatement.handle(SqlStatement.java:364)
>         at mondrian.rolap.SqlStatement.execute(SqlStatement.java:254)
>         at mondrian.rolap.RolapUtil.executeQuery(RolapUtil.java:350)
>         at mondrian.rolap.RolapUtil.executeQuery(RolapUtil.java:303)
>         at mondrian.rolap.SqlMemberSource.getMemberCount(SqlMemberSource.java:149)
>         at mondrian.rolap.SqlMemberSource.getLevelMemberCount(SqlMemberSource.java:142)
>         at mondrian.rolap.SmartMemberReader.getLevelMemberCount(SmartMemberReader.java:158)
>
> Caused by: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [260] (at 54): invalid column name: BANKS.sk: line 1 col 55 (at pos 54)
>         at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._createException(SQLExceptionSapDB.java:208)

How to specify that the dialect is Sybase?

**Comment by pgschr** [comment]
See https://github.com/pentaho/mondrian/issues/1046
